fix ForbiddenClassException for session load
com.thoughtworks.xstream.security.ForbiddenClassException: cuploader.Settings
is fixed due to incorrect xstream permissions during session loading.